[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/','@solmate=lib/solmate/src/']
auto_detect_remappings = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
